version: '3.8'
services:
  backend:
    build:
      context: ./api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./app/frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
